import { Item, Party, Invoice, Payment } from '../types';

export const LOC_FLAGSHIP_ID = '65f2a1b9a000000000000101';
export const LOC_DOWNTOWN_ID = '65f2a1b9a000000000000102';
export const LOC_WAREHOUSE_ID = '65f2a1b9a000000000000103';

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'item_1_1',
    businessId: '65f2a1b9a000000000000001',
    publicItemId: 'ITM-1001',
    name: 'Basmati Rice (1kg Pack)',
    sku: 'RICE-001',
    barcode: '8901234567890',
    category: 'Grocery',
    taxRate: 5,
    unit: 'kg',
    allowParts: true,
    salePrice: 120.0,
    purchasePrice: 95.0,
    currentStock: 310,
    minStockAlert: 10,
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&auto=format&fit=crop&q=80',
    images: [
      {
        id: 'img_rice_1',
        url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&auto=format&fit=crop&q=80',
        order: 0,
        isPrimary: true,
        name: 'Basmati Rice Premium Pack',
      },
    ],
    locations: [
      {
        locationId: LOC_FLAGSHIP_ID,
        locationName: 'Main Flagship Counter',
        salePrice: 120.0,
        purchasePrice: 95.0,
        currentStock: 45,
        minStockAlert: 10,
        isListed: true,
      },
      {
        locationId: LOC_DOWNTOWN_ID,
        locationName: 'Downtown Express Branch',
        salePrice: 128.0,
        purchasePrice: 95.0,
        currentStock: 15,
        minStockAlert: 5,
        isListed: true,
      },
      {
        locationId: LOC_WAREHOUSE_ID,
        locationName: 'Central Supply Warehouse',
        salePrice: 115.0,
        purchasePrice: 90.0,
        currentStock: 250,
        minStockAlert: 50,
        isListed: false, // Stored in warehouse, not sold directly at POS counter
      },
    ],
  },
  {
    id: 'item_1_2',
    businessId: '65f2a1b9a000000000000001',
    publicItemId: 'ITM-1002',
    name: 'Refined Sunflower Oil (1L)',
    sku: 'OIL-002',
    barcode: '8901234567891',
    category: 'Grocery',
    taxRate: 5,
    unit: 'ltr',
    allowParts: true,
    salePrice: 145.0,
    purchasePrice: 120.0,
    currentStock: 128,
    minStockAlert: 15,
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&auto=format&fit=crop&q=80',
    images: [
      {
        id: 'img_oil_1',
        url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&auto=format&fit=crop&q=80',
        order: 0,
        isPrimary: true,
        name: 'Pure Sunflower Oil',
      },
    ],
    locations: [
      {
        locationId: LOC_FLAGSHIP_ID,
        locationName: 'Main Flagship Counter',
        salePrice: 145.0,
        purchasePrice: 120.0,
        currentStock: 8,
        minStockAlert: 15,
        isListed: true,
      },
      {
        locationId: LOC_DOWNTOWN_ID,
        locationName: 'Downtown Express Branch',
        salePrice: 150.0,
        purchasePrice: 120.0,
        currentStock: 20,
        minStockAlert: 10,
        isListed: true,
      },
      {
        locationId: LOC_WAREHOUSE_ID,
        locationName: 'Central Supply Warehouse',
        salePrice: 140.0,
        purchasePrice: 115.0,
        currentStock: 100,
        minStockAlert: 25,
        isListed: false,
      },
    ],
  },
  {
    id: 'item_1_3',
    businessId: '65f2a1b9a000000000000001',
    publicItemId: 'ITM-1003',
    name: 'Wireless Optical Mouse',
    sku: 'ACC-003',
    barcode: '8901234567892',
    category: 'Electronics',
    taxRate: 18,
    unit: 'pcs',
    salePrice: 499.0,
    purchasePrice: 320.0,
    currentStock: 94,
    minStockAlert: 5,
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&auto=format&fit=crop&q=80',
    images: [
      {
        id: 'img_mouse_1',
        url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&auto=format&fit=crop&q=80',
        order: 0,
        isPrimary: true,
        name: 'Ergonomic Wireless Optical Mouse',
      },
    ],
    locations: [
      {
        locationId: LOC_FLAGSHIP_ID,
        locationName: 'Main Flagship Counter',
        salePrice: 499.0,
        purchasePrice: 320.0,
        currentStock: 24,
        minStockAlert: 5,
        isListed: true,
      },
      {
        locationId: LOC_DOWNTOWN_ID,
        locationName: 'Downtown Express Branch',
        salePrice: 549.0,
        purchasePrice: 320.0,
        currentStock: 10,
        minStockAlert: 4,
        isListed: true,
      },
      {
        locationId: LOC_WAREHOUSE_ID,
        locationName: 'Central Supply Warehouse',
        salePrice: 480.0,
        purchasePrice: 310.0,
        currentStock: 60,
        minStockAlert: 15,
        isListed: false,
      },
    ],
  },
  {
    id: 'item_1_4',
    businessId: '65f2a1b9a000000000000001',
    publicItemId: 'ITM-1004',
    name: 'USB-C Fast Charging Cable (65W)',
    sku: 'ACC-004',
    barcode: '8901234567893',
    category: 'Electronics',
    taxRate: 18,
    unit: 'pcs',
    salePrice: 249.0,
    purchasePrice: 110.0,
    currentStock: 153,
    minStockAlert: 10,
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80',
    images: [
      {
        id: 'img_cable_1',
        url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80',
        order: 0,
        isPrimary: true,
        name: 'USB-C Fast Charging Braided Cable',
      },
    ],
    locations: [
      {
        locationId: LOC_FLAGSHIP_ID,
        locationName: 'Main Flagship Counter',
        salePrice: 249.0,
        purchasePrice: 110.0,
        currentStock: 3,
        minStockAlert: 10,
        isListed: true,
      },
      {
        locationId: LOC_DOWNTOWN_ID,
        locationName: 'Downtown Express Branch',
        salePrice: 279.0,
        purchasePrice: 110.0,
        currentStock: 25,
        minStockAlert: 8,
        isListed: true,
      },
      {
        locationId: LOC_WAREHOUSE_ID,
        locationName: 'Central Supply Warehouse',
        salePrice: 230.0,
        purchasePrice: 100.0,
        currentStock: 125,
        minStockAlert: 30,
        isListed: false,
      },
    ],
  },
  {
    id: 'item_1_5',
    businessId: '65f2a1b9a000000000000001',
    publicItemId: 'ITM-1005',
    name: 'Dairy Milk Silk Chocolate (150g)',
    sku: 'SNK-005',
    barcode: '8901234567894',
    category: 'Confectionery',
    taxRate: 12,
    unit: 'pcs',
    salePrice: 90.0,
    purchasePrice: 72.0,
    currentStock: 250,
    minStockAlert: 12,
    imageUrl: 'https://images.unsplash.com/photo-1548907040-4baa42d10919?w=400&auto=format&fit=crop&q=80',
    images: [
      {
        id: 'img_choc_1',
        url: 'https://images.unsplash.com/photo-1548907040-4baa42d10919?w=400&auto=format&fit=crop&q=80',
        order: 0,
        isPrimary: true,
        name: 'Smooth Milk Chocolate Bar',
      },
    ],
    locations: [
      {
        locationId: LOC_FLAGSHIP_ID,
        locationName: 'Main Flagship Counter',
        salePrice: 90.0,
        purchasePrice: 72.0,
        currentStock: 50,
        minStockAlert: 12,
        isListed: true,
      },
      {
        locationId: LOC_DOWNTOWN_ID,
        locationName: 'Downtown Express Branch',
        salePrice: 95.0,
        purchasePrice: 72.0,
        currentStock: 40,
        minStockAlert: 10,
        isListed: true,
      },
      {
        locationId: LOC_WAREHOUSE_ID,
        locationName: 'Central Supply Warehouse',
        salePrice: 85.0,
        purchasePrice: 68.0,
        currentStock: 160,
        minStockAlert: 40,
        isListed: false,
      },
    ],
  },
  {
    id: 'item_1_6',
    businessId: '65f2a1b9a000000000000001',
    publicItemId: 'ITM-1006',
    name: 'Organic Green Tea (25 Bags)',
    sku: 'BEV-006',
    barcode: '8901234567895',
    category: 'Beverages',
    taxRate: 5,
    unit: 'box',
    salePrice: 185.0,
    purchasePrice: 135.0,
    currentStock: 89,
    minStockAlert: 8,
    imageUrl: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&auto=format&fit=crop&q=80',
    images: [
      {
        id: 'img_tea_1',
        url: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&auto=format&fit=crop&q=80',
        order: 0,
        isPrimary: true,
        name: 'Organic Green Tea Box',
      },
    ],
    locations: [
      {
        locationId: LOC_FLAGSHIP_ID,
        locationName: 'Main Flagship Counter',
        salePrice: 185.0,
        purchasePrice: 135.0,
        currentStock: 19,
        minStockAlert: 8,
        isListed: true,
      },
      {
        locationId: LOC_DOWNTOWN_ID,
        locationName: 'Downtown Express Branch',
        salePrice: 195.0,
        purchasePrice: 135.0,
        currentStock: 20,
        minStockAlert: 5,
        isListed: true,
      },
      {
        locationId: LOC_WAREHOUSE_ID,
        locationName: 'Central Supply Warehouse',
        salePrice: 175.0,
        purchasePrice: 125.0,
        currentStock: 50,
        minStockAlert: 15,
        isListed: false,
      },
    ],
  },
  {
    id: 'item_1_7',
    businessId: '65f2a1b9a000000000000001',
    publicItemId: 'ITM-1007',
    name: 'Industrial Heavy Duty Drill Machine 650W',
    sku: 'PWR-DRL-650',
    barcode: '8901234567896',
    category: 'Hardware & Tools',
    taxRate: 18,
    unit: 'set',
    salePrice: 3250.0,
    purchasePrice: 2200.0,
    currentStock: 52,
    minStockAlert: 4,
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&auto=format&fit=crop&q=80',
    images: [
      {
        id: 'img_drill_1',
        url: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&auto=format&fit=crop&q=80',
        order: 0,
        isPrimary: true,
        name: '650W Power Impact Drill',
      },
    ],
    locations: [
      {
        locationId: LOC_FLAGSHIP_ID,
        locationName: 'Main Flagship Counter',
        salePrice: 3250.0,
        purchasePrice: 2200.0,
        currentStock: 12,
        minStockAlert: 4,
        isListed: true,
      },
      {
        locationId: LOC_DOWNTOWN_ID,
        locationName: 'Downtown Express Branch',
        salePrice: 3400.0,
        purchasePrice: 2200.0,
        currentStock: 0,
        minStockAlert: 2,
        isListed: false, // Not carried at Downtown express kiosk
      },
      {
        locationId: LOC_WAREHOUSE_ID,
        locationName: 'Central Supply Warehouse',
        salePrice: 3100.0,
        purchasePrice: 2100.0,
        currentStock: 40,
        minStockAlert: 10,
        isListed: true,
      },
    ],
  },
];

export const INITIAL_PARTIES: Party[] = [
  {
    id: 'party_1_1',
    businessId: '65f2a1b9a000000000000001',
    name: 'Walk-in Retail Customer',
    type: 'CUSTOMER',
    phone: '+91 9876543210',
    currentBalance: 0,
    locationIds: [LOC_FLAGSHIP_ID, LOC_DOWNTOWN_ID, LOC_WAREHOUSE_ID],
  },
  {
    id: 'party_1_2',
    businessId: '65f2a1b9a000000000000001',
    name: 'Sharma Traders & Supermart',
    type: 'CUSTOMER',
    phone: '+91 9811223344',
    email: 'sharma.traders@gmail.com',
    gstin: '07AAAAA0000A1Z5',
    address: 'Connaught Place, New Delhi',
    currentBalance: 3594.0, // Receivable
    locationIds: [LOC_FLAGSHIP_ID],
    locationId: LOC_FLAGSHIP_ID,
    locationName: 'Main Flagship Counter',
  },
  {
    id: 'party_1_3',
    businessId: '65f2a1b9a000000000000001',
    name: 'Apex Wholesale Distributors',
    type: 'SUPPLIER',
    phone: '+91 9988776655',
    email: 'orders@apexwholesale.in',
    gstin: '07BBBBB1111B2Z6',
    address: 'Okhla Industrial Area Phase 2, New Delhi',
    currentBalance: -15200.0, // Payable
    locationIds: [LOC_WAREHOUSE_ID, LOC_FLAGSHIP_ID],
    locationId: LOC_WAREHOUSE_ID,
    locationName: 'Central Supply Warehouse',
  },
  {
    id: 'party_1_4',
    businessId: '65f2a1b9a000000000000001',
    name: 'Downtown Coffee Lounge & Cafe',
    type: 'CUSTOMER',
    phone: '+91 9877001122',
    email: 'accounts@downtowncafe.in',
    gstin: '07EEEEE5555E6Z9',
    address: 'Sector 18 Market, Noida',
    currentBalance: 8450.0,
    locationIds: [LOC_DOWNTOWN_ID],
    locationId: LOC_DOWNTOWN_ID,
    locationName: 'Downtown Express Branch',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv_101',
    businessId: '65f2a1b9a000000000000001',
    locationId: LOC_FLAGSHIP_ID,
    locationName: 'Main Flagship Counter',
    invoiceNumber: 'INV-2026-001',
    date: new Date().toISOString().split('T')[0],
    partyName: 'Walk-in Retail Customer',
    type: 'SALE',
    items: [
      {
        itemId: 'item_1_1',
        name: 'Basmati Rice (1kg Pack)',
        quantity: 2,
        unitPrice: 120.0,
        discountPercent: 0,
        taxRate: 5,
        taxAmount: 11.43,
        total: 240.0,
      },
      {
        itemId: 'item_1_5',
        name: 'Dairy Milk Silk Chocolate (150g)',
        quantity: 1,
        unitPrice: 90.0,
        discountPercent: 0,
        taxRate: 12,
        taxAmount: 9.64,
        total: 90.0,
      },
    ],
    subtotal: 308.93,
    taxTotal: 21.07,
    discountTotal: 0,
    roundOff: 0,
    grandTotal: 330.0,
    paidAmount: 330.0,
    balanceAmount: 0,
    paymentMode: 'UPI',
    status: 'PAID',
    notes: 'Counter Checkout Terminal 1',
  },
  {
    id: 'inv_102',
    businessId: '65f2a1b9a000000000000001',
    locationId: LOC_DOWNTOWN_ID,
    locationName: 'Downtown Express Branch',
    invoiceNumber: 'INV-2026-002',
    date: new Date().toISOString().split('T')[0],
    partyId: 'party_1_4',
    partyName: 'Downtown Coffee Lounge & Cafe',
    type: 'SALE',
    items: [
      {
        itemId: 'item_1_6',
        name: 'Organic Green Tea (25 Bags)',
        quantity: 5,
        unitPrice: 195.0,
        discountPercent: 0,
        taxRate: 5,
        taxAmount: 46.43,
        total: 975.0,
      },
      {
        itemId: 'item_1_2',
        name: 'Refined Sunflower Oil (1L)',
        quantity: 4,
        unitPrice: 150.0,
        discountPercent: 0,
        taxRate: 5,
        taxAmount: 28.57,
        total: 600.0,
      },
    ],
    subtotal: 1500.0,
    taxTotal: 75.0,
    discountTotal: 0,
    roundOff: 0,
    grandTotal: 1575.0,
    paidAmount: 1000.0,
    balanceAmount: 575.0,
    paymentMode: 'CASH',
    status: 'PARTIAL',
    notes: 'Downtown Express Outlet sale',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay_1',
    businessId: '65f2a1b9a000000000000001',
    date: new Date().toISOString().split('T')[0],
    partyId: 'party_1_2',
    partyName: 'Sharma Traders & Supermart',
    type: 'PAYMENT_IN',
    amount: 1500.0,
    paymentMode: 'BANK_TRANSFER',
    referenceNumber: 'HDFC98765432',
    notes: 'Part settlement for invoice ledger',
  },
];
